name: Handle secrets

on:
  workflow_dispatch

jobs:
  secretmanager:
    name: Handle secrets with Secret Manager
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_WI_PROVIDER_ID: ${{ vars.GCP_WI_PROVIDER_ID }}
      GCP_LOCATION: ${{ vars.GCP_LOCATION }}

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud Project'
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: sa-github@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          workload_identity_provider: ${{ env.GCP_WI_PROVIDER_ID }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase.config.json"
          json: ${{ secrets.FIREBASE_CONFIG_JSON }}

      - name: 'Submit firebase config json to Secret Manager with gcloud'
        run: |
          gcloud secrets versions add firebase-config \
            --data-file="./firebase.config.json"